DATA_FOLDER_NAMES = ["data"]

WINDOW_STATE = "zoomed"
WINDOW_TITLE = "ChroMS_GUI"

TAB_1_NAME = "Blank Page"
HPLC_TAB_NAME = "HPLC"
MS_TAB_NAME = "MS"

DEFAULT_WAVELENGTH = "254"
DEFAULT_MIN_INTENSITY = "0.00000"
DEFAULT_MAX_INTENSITY = "1.00000"
DEFAULT_PEAK_POS_SEQ = ""
DEFAULT_PEAK_DEV_SEQ = "0.25"
DEFAULT_CHROM_X_MIN = ""
DEFAULT_CHROM_X_MAX = ""
DEFAULT_CHROM_Y_MIN = ""
DEFAULT_CHROM_Y_MAX = ""

LEN_4_DIGIT_INT = 4
LEN_5_DIGIT_FLOAT = 5

LEN_TIME_AFTER_DEC = 5