DATA_FOLDER_NAMES = ["data"]

WINDOW_STATE = "zoomed"
WINDOW_TITLE = "ChroMS_GUI"

TAB_1_NAME = "Blank Page"
HPLC_TAB_NAME = "HPLC"
MS_TAB_NAME = "MS"

DEFAULT_WAVELENGTH = "254"
DEFAULT_MIN_INTENSITY = "0.00000"
DEFAULT_MAX_INTENSITY = "1.00000"
DEFAULT_PEAK_POS_SEQ = ""
DEFAULT_PEAK_DEV_SEQ = "0.25"

DEFAULT_FIND_MZ1_SEQ = ""
DEFAULT_FIND_MZ2_SEQ = ""

DEFAULT_CHROM_X_MIN = ""
DEFAULT_CHROM_X_MAX = ""
DEFAULT_CHROM_Y_MIN = ""
DEFAULT_CHROM_Y_MAX = ""

DEFAULT_MS_X_MIN = ""
DEFAULT_MS_X_MAX = ""
DEFAULT_MS_Y_MIN = ""
DEFAULT_MS_Y_MAX = ""

DEFAULT_MZ_TRIM_PERC = "70"
DEFAULT_MZ_RANDNUM_PERC = "15"

LEN_4_DIGIT_INT = 4
LEN_5_DIGIT_INT = 5
LEN_5_DIGIT_FLOAT = 5

LEN_TIME_AFTER_DEC = 5
LEN_MZ_AFTER_DEC = 5

DEFAULT_MATPLOTLIB_STYLE_IDENTIFIERS = ["seaborn", "ticks"]